# Generated by Django 5.1.15 on 2026-05-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(max_length=120)),
                ('published_date', models.DateField()),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'announcements_announcement',
                'ordering': ['-classification', '-published_date', 'title_en'],
            },
        ),
    ]
