# Generated by Django 5.1.15 on 2026-05-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('standard', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non Compliant'), ('in_review', 'In Review')], default='in_review', max_length=20)),
                ('finding', models.TextField(blank=True)),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compliance_complianceitem',
                'ordering': ['-classification', 'title_en'],
            },
        ),
    ]
