# Generated by Django 5.1.15 on 2026-05-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name_ar', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('mission_ar', models.CharField(blank=True, max_length=255)),
                ('mission_en', models.CharField(blank=True, max_length=255)),
                ('accent_color', models.CharField(default='#c9a227', max_length=16)),
                ('owner_department', models.CharField(max_length=64)),
                ('head_name', models.CharField(blank=True, max_length=128)),
                ('featured', models.JSONField(blank=True, default=list)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspaces_workspace',
                'ordering': ['key'],
            },
        ),
    ]
