# Generated by Django 5.1.15 on 2026-05-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('site_type', models.CharField(choices=[('facility', 'Facility'), ('unit', 'Unit'), ('asset', 'Asset')], max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('info_ar', models.CharField(blank=True, max_length=300)),
                ('info_en', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'gis_site',
                'ordering': ['-classification', 'name_en'],
            },
        ),
    ]
