# Generated by Django 5.1.15 on 2026-05-29 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveIntegerField(unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='IQD', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_budget',
                'ordering': ['-fiscal_year'],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(db_index=True, max_length=32)),
                ('category', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_expenditure',
                'ordering': ['-classification', 'department_code'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('signed', 'Signed'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('completed', 'Completed')], default='signed', max_length=16)),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_contract',
                'ordering': ['-classification', 'title_en'],
            },
        ),
    ]
