# Generated by Django 5.1.15 on 2026-05-29 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'inventory_warehouse',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=50)),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_inventoryitem',
                'ordering': ['-classification', 'name_en'],
            },
        ),
    ]
