# Generated by Django 5.1.15 on 2026-05-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('asset_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('condition', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Maintenance'), ('down', 'Down')], default='operational', max_length=20)),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets_asset',
                'ordering': ['-classification', 'name_en'],
            },
        ),
    ]
