# Generated by Django 5.1.15 on 2026-05-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('likelihood', models.PositiveSmallIntegerField()),
                ('impact', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigating', 'Mitigating'), ('closed', 'Closed')], default='open', max_length=20)),
                ('mitigation', models.TextField(blank=True)),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'risk_risk',
                'ordering': ['-classification', '-score', 'title_en'],
            },
        ),
    ]
