# Generated by Django 5.1.15 on 2026-05-30 06:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payroll_payslip',
                'ordering': ['-classification', 'employee'],
            },
        ),
    ]
