# Generated by Django 5.1.15 on 2026-05-30 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('document', 'Document'), ('spreadsheet', 'Spreadsheet'), ('image', 'Image'), ('invoice', 'Invoice'), ('other', 'Other')], default='other', max_length=12)),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('linked_module', models.CharField(blank=True, max_length=32)),
                ('linked_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachments_attachment',
                'ordering': ['-created_at'],
            },
        ),
    ]
