# Generated by Django 5.1.15 on 2026-05-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('rating', models.CharField(choices=[('outstanding', 'Outstanding'), ('good', 'Good'), ('needs_improvement', 'Needs Improvement')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'performance_performancereview',
                'ordering': ['-classification', 'employee'],
            },
        ),
    ]
