# Generated by Django 5.1.15 on 2026-05-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name_ar', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='personnel.department')),
            ],
            options={
                'db_table': 'personnel_department',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('rank_ar', models.CharField(blank=True, max_length=64)),
                ('rank_en', models.CharField(blank=True, max_length=64)),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('leave', 'On leave'), ('mission', 'On mission')], default='active', max_length=12)),
                ('attendance', models.PositiveSmallIntegerField(default=100)),
                ('joined_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=32)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='personnel.department')),
            ],
            options={
                'db_table': 'personnel_person',
                'ordering': ['-classification', 'name_en'],
            },
        ),
    ]
