# Generated by Django 5.1.15 on 2026-05-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('classification', models.IntegerField(choices=[(1, 'Public'), (2, 'Restricted'), (3, 'Secret'), (4, 'Top_Secret')], db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meetings_meeting',
                'ordering': ['-classification', 'start_at'],
            },
        ),
    ]
